/* 
Name: noteName,
       modified: new Date().toDateString(),
       folderId,
       content

body: JSON.stringify({ name: folderName })
*/

CREATE TABLE folders (
  --id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL
);

CREATE TABLE notes (
  --id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  modified TIMESTAMP NOT NULL DEFAULT now(),
  content TEXT NOT NULL,
  folderId INTEGER REFERENCES folders(id) ON DELETE CASCADE NOT NULL
);